//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silverlight_Sample
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// Context for the RIA application.
    /// </summary>
    /// <remarks>
    /// This context extends the base to make application services and types available
    /// for consumption from code and xaml.
    /// </remarks>
    public sealed partial class WebContext : WebContextBase
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the WebContext class.
        /// </summary>
        public WebContext()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the context that is registered as a lifetime object with the current application.
        /// </summary>
        /// <exception cref="InvalidOperationException"> is thrown if there is no current application,
        /// no contexts have been added, or more than one context has been added.
        /// </exception>
        /// <seealso cref="System.Windows.Application.ApplicationLifetimeObjects"/>
        public new static WebContext Current
        {
            get
            {
                return ((WebContext)(WebContextBase.Current));
            }
        }
    }
}
namespace WcfRia_HostWebSite.Services
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// The DomainContext corresponding to the 'SampleWcfRiaService' DomainService.
    /// </summary>
    public sealed partial class SampleWcfRiaContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="SampleWcfRiaContext"/> class.
        /// </summary>
        public SampleWcfRiaContext() : 
                this(new WebDomainClient<ISampleWcfRiaServiceContract>(new Uri("WcfRia_HostWebSite-Services-SampleWcfRiaService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="SampleWcfRiaContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The SampleWcfRiaService service URI.</param>
        public SampleWcfRiaContext(Uri serviceUri) : 
                this(new WebDomainClient<ISampleWcfRiaServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="SampleWcfRiaContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public SampleWcfRiaContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetMessage' method of the DomainService.
        /// </summary>
        /// <param name="key">The value for the 'key' parameter of this action.</param>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<string> GetMessage(string key, Action<InvokeOperation<string>> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("key", key);
            this.ValidateMethod("GetMessage", parameters);
            return ((InvokeOperation<string>)(this.InvokeOperation("GetMessage", typeof(string), parameters, true, callback, userState)));
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetMessage' method of the DomainService.
        /// </summary>
        /// <param name="key">The value for the 'key' parameter of this action.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<string> GetMessage(string key)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("key", key);
            this.ValidateMethod("GetMessage", parameters);
            return ((InvokeOperation<string>)(this.InvokeOperation("GetMessage", typeof(string), parameters, true, null, null)));
        }
        
        /// <summary>
        /// Asynchronously invokes the 'MakeError' method of the DomainService.
        /// </summary>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation MakeError(Action<InvokeOperation> callback, object userState)
        {
            this.ValidateMethod("MakeError", null);
            return this.InvokeOperation("MakeError", typeof(void), null, true, callback, userState);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'MakeError' method of the DomainService.
        /// </summary>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation MakeError()
        {
            this.ValidateMethod("MakeError", null);
            return this.InvokeOperation("MakeError", typeof(void), null, true, null, null);
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new SampleWcfRiaContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'SampleWcfRiaService' DomainService.
        /// </summary>
        [ServiceContract()]
        public interface ISampleWcfRiaServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetMessage' operation.
            /// </summary>
            /// <param name="key">The value for the 'key' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/SampleWcfRiaService/GetMessageDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/SampleWcfRiaService/GetMessage", ReplyAction="http://tempuri.org/SampleWcfRiaService/GetMessageResponse")]
            IAsyncResult BeginGetMessage(string key, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetMessage'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetMessage'.</param>
            /// <returns>The 'String' returned from the 'GetMessage' operation.</returns>
            string EndGetMessage(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'MakeError' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/SampleWcfRiaService/MakeErrorDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/SampleWcfRiaService/MakeError", ReplyAction="http://tempuri.org/SampleWcfRiaService/MakeErrorResponse")]
            IAsyncResult BeginMakeError(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginMakeError'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginMakeError'.</param>
            void EndMakeError(IAsyncResult result);
        }
        
        internal sealed class SampleWcfRiaContextEntityContainer : EntityContainer
        {
            
            public SampleWcfRiaContextEntityContainer()
            {
            }
        }
    }
}
